// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-lxUXrLdfavGEmhGTsBQfdLGxpnMaNy0',
    appId: '1:191398930487:web:de774a7f795f49660cb7b2',
    messagingSenderId: '191398930487',
    projectId: 'calculadora-da-gabi',
    authDomain: 'calculadora-da-gabi.firebaseapp.com',
    storageBucket: 'calculadora-da-gabi.appspot.com',
    measurementId: 'G-31GBLLH90L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRf0jFQu8t3L7n3zwSuyZfD7Bw9LhsE1c',
    appId: '1:191398930487:android:88269038b2deed4a0cb7b2',
    messagingSenderId: '191398930487',
    projectId: 'calculadora-da-gabi',
    storageBucket: 'calculadora-da-gabi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBULEZqjRQPhjX81aYlx68mJU4411AkaOE',
    appId: '1:191398930487:ios:e4bcec6551c0f5c40cb7b2',
    messagingSenderId: '191398930487',
    projectId: 'calculadora-da-gabi',
    storageBucket: 'calculadora-da-gabi.appspot.com',
    iosBundleId: 'com.electrogear.calculadoraDaGabi',
  );
}
